#!/bin/sh
# ebindent: indent source code, according to the edbrowse style.
# Usage: ebindent <SOURCEFILE> ...
#
# Which directory contains this script?
progdir="$(dirname $0)"
# There better be a file named indent.pro in the same directory, because
# that's what indent will try to use.
export INDENT_PROFILE="$progdir/indent.pro"
exec indent "$@"
